parameters:
    base.case.twig_extension.class: BaseBundle\Twig\Extension\CaseExtension
    base.light.twig_extension.class: BaseBundle\Twig\Extension\LightExtension
    base.setting.twig_extension.class: BaseBundle\Twig\Extension\SettingExtension
    base.markdown.twig_extension.class: BaseBundle\Twig\Extension\MarkdownExtension

services:

    base.case.twig_extension:
        class: '%base.case.twig_extension.class%'
        tags:
            - { name: twig.extension }

    base.light.twig_extension:
        class: '%base.light.twig_extension.class%'
        parent: base.twig_extension
        tags:
            - { name: twig.extension }

    base.setting.twig_extension:
        class: '%base.setting.twig_extension.class%'
        tags:
            - { name: twig.extension }

    base.markdown.twig_extension:
        class: '%base.markdown.twig_extension.class%'
        tags:
            - { name: twig.extension }
